#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEntrepot
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nicaragua")]
	public partial class EntrepotBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSize(Size instance);
    partial void UpdateSize(Size instance);
    partial void DeleteSize(Size instance);
    partial void InsertWrapper(Wrapper instance);
    partial void UpdateWrapper(Wrapper instance);
    partial void DeleteWrapper(Wrapper instance);
    partial void InsertBlend(Blend instance);
    partial void UpdateBlend(Blend instance);
    partial void DeleteBlend(Blend instance);
    partial void Inserttb_liga(tb_liga instance);
    partial void Updatetb_liga(tb_liga instance);
    partial void Deletetb_liga(tb_liga instance);
    partial void Inserttb_vitola(tb_vitola instance);
    partial void Updatetb_vitola(tb_vitola instance);
    partial void Deletetb_vitola(tb_vitola instance);
    partial void Inserttb_capa(tb_capa instance);
    partial void Updatetb_capa(tb_capa instance);
    partial void Deletetb_capa(tb_capa instance);
    partial void InsertPersonal(Personal instance);
    partial void UpdatePersonal(Personal instance);
    partial void DeletePersonal(Personal instance);
    partial void InsertProduction_Daily(Production_Daily instance);
    partial void UpdateProduction_Daily(Production_Daily instance);
    partial void DeleteProduction_Daily(Production_Daily instance);
    partial void InsertStock(Stock instance);
    partial void UpdateStock(Stock instance);
    partial void DeleteStock(Stock instance);
    partial void InsertTobacco(Tobacco instance);
    partial void UpdateTobacco(Tobacco instance);
    partial void DeleteTobacco(Tobacco instance);
    #endregion
		
		public EntrepotBDDataContext() : 
				base(global::MyEntrepot.Properties.Settings.Default.nicaraguaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntrepotBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntrepotBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntrepotBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntrepotBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Size> Sizes
		{
			get
			{
				return this.GetTable<Size>();
			}
		}
		
		public System.Data.Linq.Table<Wrapper> Wrappers
		{
			get
			{
				return this.GetTable<Wrapper>();
			}
		}
		
		public System.Data.Linq.Table<Blend> Blends
		{
			get
			{
				return this.GetTable<Blend>();
			}
		}
		
		public System.Data.Linq.Table<tb_liga> tb_ligas
		{
			get
			{
				return this.GetTable<tb_liga>();
			}
		}
		
		public System.Data.Linq.Table<tb_vitola> tb_vitolas
		{
			get
			{
				return this.GetTable<tb_vitola>();
			}
		}
		
		public System.Data.Linq.Table<tb_capa> tb_capas
		{
			get
			{
				return this.GetTable<tb_capa>();
			}
		}
		
		public System.Data.Linq.Table<View_TobaccoCatalog> View_TobaccoCatalogs
		{
			get
			{
				return this.GetTable<View_TobaccoCatalog>();
			}
		}
		
		public System.Data.Linq.Table<View_Personal> View_Personals
		{
			get
			{
				return this.GetTable<View_Personal>();
			}
		}
		
		public System.Data.Linq.Table<Personal> Personals
		{
			get
			{
				return this.GetTable<Personal>();
			}
		}
		
		public System.Data.Linq.Table<Production_Daily> Production_Dailies
		{
			get
			{
				return this.GetTable<Production_Daily>();
			}
		}
		
		public System.Data.Linq.Table<Stock> Stocks
		{
			get
			{
				return this.GetTable<Stock>();
			}
		}
		
		public System.Data.Linq.Table<View_Production_Daily> View_Production_Dailies
		{
			get
			{
				return this.GetTable<View_Production_Daily>();
			}
		}
		
		public System.Data.Linq.Table<View_Stock> View_Stocks
		{
			get
			{
				return this.GetTable<View_Stock>();
			}
		}
		
		public System.Data.Linq.Table<View_Stock_Detail> View_Stock_Details
		{
			get
			{
				return this.GetTable<View_Stock_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Tobacco> Tobaccos
		{
			get
			{
				return this.GetTable<Tobacco>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Size")]
	public partial class Size : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Size;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_SizeChanging(int value);
    partial void Onid_SizeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Size()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Size", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Size
		{
			get
			{
				return this._id_Size;
			}
			set
			{
				if ((this._id_Size != value))
				{
					this.Onid_SizeChanging(value);
					this.SendPropertyChanging();
					this._id_Size = value;
					this.SendPropertyChanged("id_Size");
					this.Onid_SizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Wrapper")]
	public partial class Wrapper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Wrapper;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_WrapperChanging(int value);
    partial void Onid_WrapperChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Wrapper()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Wrapper", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Wrapper
		{
			get
			{
				return this._id_Wrapper;
			}
			set
			{
				if ((this._id_Wrapper != value))
				{
					this.Onid_WrapperChanging(value);
					this.SendPropertyChanging();
					this._id_Wrapper = value;
					this.SendPropertyChanged("id_Wrapper");
					this.Onid_WrapperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Blend")]
	public partial class Blend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Blend;
		
		private string _name;
		
		private string _descrip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_BlendChanging(int value);
    partial void Onid_BlendChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescripChanging(string value);
    partial void OndescripChanged();
    #endregion
		
		public Blend()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Blend", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Blend
		{
			get
			{
				return this._id_Blend;
			}
			set
			{
				if ((this._id_Blend != value))
				{
					this.Onid_BlendChanging(value);
					this.SendPropertyChanging();
					this._id_Blend = value;
					this.SendPropertyChanged("id_Blend");
					this.Onid_BlendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrip", DbType="VarChar(50)")]
		public string descrip
		{
			get
			{
				return this._descrip;
			}
			set
			{
				if ((this._descrip != value))
				{
					this.OndescripChanging(value);
					this.SendPropertyChanging();
					this._descrip = value;
					this.SendPropertyChanged("descrip");
					this.OndescripChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.tb_liga")]
	public partial class tb_liga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_liga;
		
		private string _liga;
		
		private string _habano;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ligaChanging(int value);
    partial void Onid_ligaChanged();
    partial void OnligaChanging(string value);
    partial void OnligaChanged();
    partial void OnhabanoChanging(string value);
    partial void OnhabanoChanged();
    #endregion
		
		public tb_liga()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_liga", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_liga
		{
			get
			{
				return this._id_liga;
			}
			set
			{
				if ((this._id_liga != value))
				{
					this.Onid_ligaChanging(value);
					this.SendPropertyChanging();
					this._id_liga = value;
					this.SendPropertyChanged("id_liga");
					this.Onid_ligaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liga", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string liga
		{
			get
			{
				return this._liga;
			}
			set
			{
				if ((this._liga != value))
				{
					this.OnligaChanging(value);
					this.SendPropertyChanging();
					this._liga = value;
					this.SendPropertyChanged("liga");
					this.OnligaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habano", DbType="VarChar(2)")]
		public string habano
		{
			get
			{
				return this._habano;
			}
			set
			{
				if ((this._habano != value))
				{
					this.OnhabanoChanging(value);
					this.SendPropertyChanging();
					this._habano = value;
					this.SendPropertyChanged("habano");
					this.OnhabanoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.tb_vitola")]
	public partial class tb_vitola : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vitola;
		
		private string _vitola;
		
		private string _habano;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vitolaChanging(int value);
    partial void Onid_vitolaChanged();
    partial void OnvitolaChanging(string value);
    partial void OnvitolaChanged();
    partial void OnhabanoChanging(string value);
    partial void OnhabanoChanged();
    #endregion
		
		public tb_vitola()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vitola", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_vitola
		{
			get
			{
				return this._id_vitola;
			}
			set
			{
				if ((this._id_vitola != value))
				{
					this.Onid_vitolaChanging(value);
					this.SendPropertyChanging();
					this._id_vitola = value;
					this.SendPropertyChanged("id_vitola");
					this.Onid_vitolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitola", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vitola
		{
			get
			{
				return this._vitola;
			}
			set
			{
				if ((this._vitola != value))
				{
					this.OnvitolaChanging(value);
					this.SendPropertyChanging();
					this._vitola = value;
					this.SendPropertyChanged("vitola");
					this.OnvitolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habano", DbType="VarChar(2)")]
		public string habano
		{
			get
			{
				return this._habano;
			}
			set
			{
				if ((this._habano != value))
				{
					this.OnhabanoChanging(value);
					this.SendPropertyChanging();
					this._habano = value;
					this.SendPropertyChanged("habano");
					this.OnhabanoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.tb_capa")]
	public partial class tb_capa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_capa;
		
		private string _capa;
		
		private string _habano;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_capaChanging(int value);
    partial void Onid_capaChanged();
    partial void OncapaChanging(string value);
    partial void OncapaChanged();
    partial void OnhabanoChanging(string value);
    partial void OnhabanoChanged();
    #endregion
		
		public tb_capa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_capa", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_capa
		{
			get
			{
				return this._id_capa;
			}
			set
			{
				if ((this._id_capa != value))
				{
					this.Onid_capaChanging(value);
					this.SendPropertyChanging();
					this._id_capa = value;
					this.SendPropertyChanged("id_capa");
					this.Onid_capaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capa", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string capa
		{
			get
			{
				return this._capa;
			}
			set
			{
				if ((this._capa != value))
				{
					this.OncapaChanging(value);
					this.SendPropertyChanging();
					this._capa = value;
					this.SendPropertyChanged("capa");
					this.OncapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habano", DbType="VarChar(2)")]
		public string habano
		{
			get
			{
				return this._habano;
			}
			set
			{
				if ((this._habano != value))
				{
					this.OnhabanoChanging(value);
					this.SendPropertyChanging();
					this._habano = value;
					this.SendPropertyChanged("habano");
					this.OnhabanoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.View_TobaccoCatalog")]
	public partial class View_TobaccoCatalog
	{
		
		private string _name;
		
		private string _Size;
		
		private string _Wrapper;
		
		private string _Blend;
		
		public View_TobaccoCatalog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrapper", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Wrapper
		{
			get
			{
				return this._Wrapper;
			}
			set
			{
				if ((this._Wrapper != value))
				{
					this._Wrapper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blend", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Blend
		{
			get
			{
				return this._Blend;
			}
			set
			{
				if ((this._Blend != value))
				{
					this._Blend = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.View_Personal")]
	public partial class View_Personal
	{
		
		private string _name;
		
		private string _position;
		
		public View_Personal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Personal")]
	public partial class Personal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Personal;
		
		private string _name;
		
		private string _position;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_PersonalChanging(int value);
    partial void Onid_PersonalChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    #endregion
		
		public Personal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Personal", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Personal
		{
			get
			{
				return this._id_Personal;
			}
			set
			{
				if ((this._id_Personal != value))
				{
					this.Onid_PersonalChanging(value);
					this.SendPropertyChanging();
					this._id_Personal = value;
					this.SendPropertyChanged("id_Personal");
					this.Onid_PersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Production_Daily")]
	public partial class Production_Daily : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Prod_Daily;
		
		private int _product;
		
		private int _personal;
		
		private decimal _cost_Bonchero;
		
		private decimal _cost_Rolero;
		
		private System.DateTime _Date;
		
		private int _quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_Prod_DailyChanging(int value);
    partial void Onid_Prod_DailyChanged();
    partial void OnproductChanging(int value);
    partial void OnproductChanged();
    partial void OnpersonalChanging(int value);
    partial void OnpersonalChanged();
    partial void Oncost_BoncheroChanging(decimal value);
    partial void Oncost_BoncheroChanged();
    partial void Oncost_RoleroChanging(decimal value);
    partial void Oncost_RoleroChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
		
		public Production_Daily()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Prod_Daily", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Prod_Daily
		{
			get
			{
				return this._id_Prod_Daily;
			}
			set
			{
				if ((this._id_Prod_Daily != value))
				{
					this.Onid_Prod_DailyChanging(value);
					this.SendPropertyChanging();
					this._id_Prod_Daily = value;
					this.SendPropertyChanged("id_Prod_Daily");
					this.Onid_Prod_DailyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int product
		{
			get
			{
				return this._product;
			}
			set
			{
				if ((this._product != value))
				{
					this.OnproductChanging(value);
					this.SendPropertyChanging();
					this._product = value;
					this.SendPropertyChanged("product");
					this.OnproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int personal
		{
			get
			{
				return this._personal;
			}
			set
			{
				if ((this._personal != value))
				{
					this.OnpersonalChanging(value);
					this.SendPropertyChanging();
					this._personal = value;
					this.SendPropertyChanged("personal");
					this.OnpersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_Bonchero", DbType="Money NOT NULL")]
		public decimal cost_Bonchero
		{
			get
			{
				return this._cost_Bonchero;
			}
			set
			{
				if ((this._cost_Bonchero != value))
				{
					this.Oncost_BoncheroChanging(value);
					this.SendPropertyChanging();
					this._cost_Bonchero = value;
					this.SendPropertyChanged("cost_Bonchero");
					this.Oncost_BoncheroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost_Rolero", DbType="Money NOT NULL")]
		public decimal cost_Rolero
		{
			get
			{
				return this._cost_Rolero;
			}
			set
			{
				if ((this._cost_Rolero != value))
				{
					this.Oncost_RoleroChanging(value);
					this.SendPropertyChanging();
					this._cost_Rolero = value;
					this.SendPropertyChanged("cost_Rolero");
					this.Oncost_RoleroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.Stock")]
	public partial class Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Depot;
		
		private int _product;
		
		private int _stock1;
		
		private System.DateTime _dateE;
		
		private int _referDaily;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_DepotChanging(int value);
    partial void Onid_DepotChanged();
    partial void OnproductChanging(int value);
    partial void OnproductChanged();
    partial void Onstock1Changing(int value);
    partial void Onstock1Changed();
    partial void OndateEChanging(System.DateTime value);
    partial void OndateEChanged();
    partial void OnreferDailyChanging(int value);
    partial void OnreferDailyChanged();
    #endregion
		
		public Stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Depot", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Depot
		{
			get
			{
				return this._id_Depot;
			}
			set
			{
				if ((this._id_Depot != value))
				{
					this.Onid_DepotChanging(value);
					this.SendPropertyChanging();
					this._id_Depot = value;
					this.SendPropertyChanged("id_Depot");
					this.Onid_DepotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product", DbType="Int NOT NULL")]
		public int product
		{
			get
			{
				return this._product;
			}
			set
			{
				if ((this._product != value))
				{
					this.OnproductChanging(value);
					this.SendPropertyChanging();
					this._product = value;
					this.SendPropertyChanged("product");
					this.OnproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="stock", Storage="_stock1", DbType="Int NOT NULL")]
		public int stock1
		{
			get
			{
				return this._stock1;
			}
			set
			{
				if ((this._stock1 != value))
				{
					this.Onstock1Changing(value);
					this.SendPropertyChanging();
					this._stock1 = value;
					this.SendPropertyChanged("stock1");
					this.Onstock1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateE", DbType="Date NOT NULL")]
		public System.DateTime dateE
		{
			get
			{
				return this._dateE;
			}
			set
			{
				if ((this._dateE != value))
				{
					this.OndateEChanging(value);
					this.SendPropertyChanging();
					this._dateE = value;
					this.SendPropertyChanged("dateE");
					this.OndateEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referDaily", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int referDaily
		{
			get
			{
				return this._referDaily;
			}
			set
			{
				if ((this._referDaily != value))
				{
					this.OnreferDailyChanging(value);
					this.SendPropertyChanging();
					this._referDaily = value;
					this.SendPropertyChanged("referDaily");
					this.OnreferDailyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.View_Production_Daily")]
	public partial class View_Production_Daily
	{
		
		private string _Product;
		
		private string _Personal;
		
		private string _Cost_Bonchero;
		
		private string _Cost_Rolero;
		
		private System.DateTime _Date;
		
		private int _quantity;
		
		public View_Production_Daily()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Personal
		{
			get
			{
				return this._Personal;
			}
			set
			{
				if ((this._Personal != value))
				{
					this._Personal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cost Bonchero]", Storage="_Cost_Bonchero", DbType="NVarChar(4000)")]
		public string Cost_Bonchero
		{
			get
			{
				return this._Cost_Bonchero;
			}
			set
			{
				if ((this._Cost_Bonchero != value))
				{
					this._Cost_Bonchero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Cost Rolero]", Storage="_Cost_Rolero", DbType="NVarChar(4000)")]
		public string Cost_Rolero
		{
			get
			{
				return this._Cost_Rolero;
			}
			set
			{
				if ((this._Cost_Rolero != value))
				{
					this._Cost_Rolero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.View_Stock")]
	public partial class View_Stock
	{
		
		private string _Product;
		
		private System.Nullable<int> _Qty;
		
		public View_Stock()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
		public System.Nullable<int> Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this._Qty = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="roberto.View_Stock_Detail")]
	public partial class View_Stock_Detail
	{
		
		private string _Product;
		
		private int _Qty;
		
		private System.DateTime _Date;
		
		public View_Stock_Detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int NOT NULL")]
		public int Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this._Qty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tobacco")]
	public partial class Tobacco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _size;
		
		private int _wrapper;
		
		private int _blend;
		
		private string _name;
		
		private int _id_Tobacco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsizeChanging(int value);
    partial void OnsizeChanged();
    partial void OnwrapperChanging(int value);
    partial void OnwrapperChanged();
    partial void OnblendChanging(int value);
    partial void OnblendChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onid_TobaccoChanging(int value);
    partial void Onid_TobaccoChanged();
    #endregion
		
		public Tobacco()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int NOT NULL")]
		public int size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wrapper", DbType="Int NOT NULL")]
		public int wrapper
		{
			get
			{
				return this._wrapper;
			}
			set
			{
				if ((this._wrapper != value))
				{
					this.OnwrapperChanging(value);
					this.SendPropertyChanging();
					this._wrapper = value;
					this.SendPropertyChanged("wrapper");
					this.OnwrapperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blend", DbType="Int NOT NULL")]
		public int blend
		{
			get
			{
				return this._blend;
			}
			set
			{
				if ((this._blend != value))
				{
					this.OnblendChanging(value);
					this.SendPropertyChanging();
					this._blend = value;
					this.SendPropertyChanged("blend");
					this.OnblendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Tobacco", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Tobacco
		{
			get
			{
				return this._id_Tobacco;
			}
			set
			{
				if ((this._id_Tobacco != value))
				{
					this.Onid_TobaccoChanging(value);
					this.SendPropertyChanging();
					this._id_Tobacco = value;
					this.SendPropertyChanged("id_Tobacco");
					this.Onid_TobaccoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
